# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-21 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2017, 12, 21, 20, 33, 40, 587394)),
        ),
    ]
