# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_auto_20180111_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='no desc', max_length=255),
        ),
    ]
