# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0006_auto_20180112_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservice',
            old_name='descriptio',
            new_name='description',
        ),
    ]
