# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginsys', '0007_auto_20180112_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userservice',
            old_name='serviceid',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='userservice',
            old_name='userid',
            new_name='user',
        ),
        migrations.AddField(
            model_name='service',
            name='users',
            field=models.ManyToManyField(through='loginsys.UserService', to=settings.AUTH_USER_MODEL),
        ),
    ]
