# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0008_auto_20180113_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
