# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0009_auto_20180113_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(default='http://bit.ly/2mx1zI0', upload_to=''),
        ),
    ]
