# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0011_auto_20180113_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(default='order/images/333.png', upload_to='order/images'),
        ),
    ]
