# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0012_auto_20180113_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
