# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0013_auto_20180113_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='desc_picture',
            field=models.ImageField(default='order/images/333.png', upload_to='order/images'),
        ),
    ]
